### ISSUE TITLE
Why GET with body?

### ISSUE THREAD

**Issue by raztud** [fingerbank/javascript-client#1]
Really, what was in your mind when you implemented GET with body?
https://tools.ietf.org/html/rfc2616#section-9.3

> The GET method means retrieve whatever information (in the form of an
   entity) is identified by the Request-URI.

**Comment by julsemaan** [comment]
Hi @raztud 

First this is more an API issue than related to the Javascript client as it follows the API spec declared here:
https://fingerbank.inverse.ca/api_doc/1/combinations/interogate.html

This choice was made in the optic of respecting the semantic of the HTTP verb where you are getting a combination and not creating one.

Given the API is being reworked for version 2, it is taken into consideration to move this to a POST to be more compliant with proxies that could cache GET requests without taking in consideration the content of the body.

I'll close this as its not directly related to the Javascript client but as stated above, this concern is already being addressed for the second version of the API. 

For any additional API related questions, I suggest you use the Fingerbank mailing list

**Comment by raztud** [comment]
@julsemaan thank you for the response. actually i wanted to complain about the api, but this was the only place where i could do it. 
Indeed, the issue is not related with the js client. The problem I have is tornado async client doesn't accept at all a GET with body because it is not standard and I have to change my software stack. 
I hope in the API v2 will be decisions more realistic and compliant with the RFCs.

**Comment by julsemaan** [comment]
@raztud 

For those cases, we do support GET without payload where you pass the arguments using query parameters

You can check it out here: https://fingerbank.inverse.ca/api_doc/1/combinations/interogate.html

**Comment by julsemaan** [comment]
Also side note on the RFC, it doesn't explicitly define that the request body of a GET is prohibited and actually doesn't state what should happen with that body should it be present.

HTTP/1.1 (RFC2616) defines that a webserver should ignore the body, but then in an RFC, "should not" doesn't mean "cannot" and implies that one can do it if he considers seriously the question before transgressing that rule

Quick research will lead you to find that this isn't as uncommon as you would think, although we got the idea from the less popular OpenDaylight project, it is used broadly by other very popular APIs including [ElasticSearch](https://www.elastic.co/guide/en/elasticsearch/guide/current/_empty_search.html) 

So there is no consensus around whether or not one should do this and the new HTTP/1.1 RFC7230 has been «relaxed» on this matter where rule that says you should ignore the GET body has been removed

I'd be happy to continue the conversation on the [mailing list](https://fingerbank.org/support.html) around this so that its properly addressed in the second version of the API
